### ISSUE TITLE
Add/Update Social Media Links for Team members and Partners

### ISSUE THREAD

**Issue by kilemensi** [CodeForAfrica/ui#189]
Add a social media links sections to team member and partners pages in NetlifyCMS. Social media links should include:

 - Twitter
 - Slack
 - LinkedIn
 - Facebook
 - Instagram
 - GitHub

These links should then be used in the CONNECT component per designs.

![Image](https://user-images.githubusercontent.com/1779590/182555285-177377c5-edaa-456a-947c-21e472f3a781.png)

**Comment by kelvinkipruto** [comment]
I'm not sure if creating a new component is the best option for this, or rather modifying the existing one to allow for both connecting and sharing. Currently, the [component](https://github.com/CodeForAfrica/ui/blob/main/apps/codeforafrica/src/components/ShareBarButton/ShareBarButton.js#:~:text=import%20%7B,react%2Dshare%22%3B) uses [react-share](https://www.npmjs.com/package/react-share) for the sharing which only allows sharing and not following or connecting. My suggestion is to modify the current existing one and pass a value down through props say `intent` which can either be `share` or `connect` to determine if it is a share or connection request, then handle if from there.

**Comment by kilemensi** [comment]
Heita.

I think lets start with separate components: ConnectBar and ConnectBarButton. Then once have that working, we can see how similar they're and if it makes sense keeping them separate or combining them.
