### ISSUE TITLE
Pull hero from CMS

### ISSUE THREAD

**Issue by kilemensi** [CodeForAfrica/ui#212]
👇 pages have hard-coded hero content. Reuse/extend `getHero` to cover pulling hero these pages as well as update `lib/index.js` to use CMS hero for these pages:

 - `/projects`,
 - `/opportunites`,
 - `/contant`,
 - `/imprint`, and
 - `/privacy`.

**Comment by esirK** [comment]
@kilemensi  I'm picking up this.
