### ISSUE TITLE
Fix connect on partner pages

### ISSUE THREAD

**Issue by kilemensi** [CodeForAfrica/ui#213]
As a follow up to https://github.com/CodeForAfrica/ui/pull/191, fix **Connect** social media links on partners pages.

**Comment by kelvinkipruto** [comment]
@kilemensi If I remember correctly, partners should only have facebook, twitter and linkedIn connection options right?

**Comment by kilemensi** [comment]
> @kilemensi If I remember correctly, partners should only have facebook, twitter and linkedIn connection options right?

🤔 ... I think lets allow all options (similar to individual) @kelvinkipruto . Content editor can choose which one to use & which one to ignore.
