### ISSUE TITLE
Our partner link

### ISSUE THREAD

**Issue by kilemensi** [CodeForAfrica/ui#220]
Similar to **Get Involved** below it, Add a button link to **Our Partners** on the homepage. The link details should be:

  - `content`: Meet our Partners
  - `href`: /about/partners

Both of the above should be editable in the CMS (again, similar to Get Involved).

![Image](https://user-images.githubusercontent.com/1779590/185607637-68f61284-3de4-4162-aa3b-9b344c492d25.jpg)

**Comment by esirK** [comment]
Picking up this @kilemensi
