### ISSUE TITLE
Review lib/index.js for any remaining hard-coded strings

### ISSUE THREAD

**Issue by kilemensi** [CodeForAfrica/ui#242]
Now we have full integration with CMSes, it's time to review and remove all remaining hard-coded strings in code. Specifically, we should comb through `lib/index.js`.

**Comment by kelvinkipruto** [comment]
@kilemensi Going through this, and it most of the hard-coded titles are section titles and slugs.

**Comment by kilemensi** [comment]
> @kilemensi Going through this, ...

Correct @kelvinkipruto. Can we move them to their respective sections in the NetlifyCMS?

**Comment by kelvinkipruto** [comment]
@kilemensi how do you propose we do this? I was thinking of a different collection say `Sections` then add the `title` and `slug`, for each possible section, but then I realised most of them are repeated irregardless of the section they are in, example `hero` , `related-stories`, and `news-stories`,

**Comment by kilemensi** [comment]
Give me a real example of what you've found @kelvinkipruto and lets discuss it.

**Comment by kilemensi** [comment]
Making any headway on this @kelvinkipruto ?

**Comment by kelvinkipruto** [comment]
@kilemensi, I have run into a few issues here. The major one of them is related to hidden fields in Netlify CMS. It looks like they don't appear in the .md file as described [here](https://stackoverflow.com/a/72323574) and also some open issues regarding it like [this](https://github.com/netlify-templates/gatsby-starter-netlify-cms/issues/843). An example in our case would be [here](https://github.com/CodeForAfrica/ui/blob/1bde1bc9b96005e0e1db2ff93bf4cf967fc123fd/apps/codeforafrica/src/pages/api/admin/config.js#L1637-L1642) where the hidden fields are not added to the [.md](https://github.com/CodeForAfrica/ui/blob/1bde1bc9b96005e0e1db2ff93bf4cf967fc123fd/apps/codeforafrica/content/settings/general.md) file.

**Comment by kilemensi** [comment]
> @kilemensi, I have run into a few issues here. The
>

Hey @kelvinkipruto.

Before I spend some time looking into that, how're hidden fields related to this current issue?

**Comment by kelvinkipruto** [comment]
@kilemensi We need to move the hard-coded slugs and titles to the cms as hidden fields.

**Comment by kilemensi** [comment]
> @kilemensi We need to move the hard-coded slugs and titles to the cms as hidden fields.

Do we? Did you try https://github.com/CodeForAfrica/ui/pull/246#discussion_r963592491?

i.e. as long as you include `slug` in fields array, the `getCollectionBySlug` method will return the slug as part of the result.

Can you share an example where that doesn't work?

**Comment by kelvinkipruto** [comment]
@kilemensi Yes I have tried it. In this case the slug returned will be `about` since  the slug in `getCollectionBySlug` is derived from the [filename](https://github.com/CodeForAfrica/ui/blob/ed09ce7b7ab86baa7a12b8b427d794cb6d188ccc/apps/codeforafrica/src/lib/api.netlify-cms/utils.js#L25-L26:~:text=const%20realSlug%20%3D%20slug.replace(/%5C.md%24/%2C%20%22%22)%3B). The correct slug should be `get-in-touch`

**Comment by kilemensi** [comment]
> @kilemensi Yes I have tried it. In ...
>

I've update #246 to handle this case using `get-in-touch` as an example @kelvinkipruto

**Comment by kelvinkipruto** [comment]
@kilemensi  Let me have a look

**Comment by kilemensi** [comment]
> @kilemensi Let me have a look
>

And @kelvinkipruto ?
