### ISSUE TITLE
@/charterafrica/components/Explainer

### ISSUE THREAD

**Issue by kilemensi** [CodeForAfrica/ui#301]
## Description

Implement the Explainer component: `title`, `description` & `image` props. Also create a _block_ in the CMS to match expected data structure.

## Screenshot

![Image](https://user-images.githubusercontent.com/1779590/213630371-9909d6de-5649-43ac-ac0c-a18ed58e4e01.png)

**Comment by kilemensi** [comment]
@koechkevin can you start with this (if it makes sense)?

**Comment by koechkevin** [comment]
Going through designs on figma and I don't seem to find this. @kilemensi

**Comment by koechkevin** [comment]
Got it!
