### ISSUE TITLE
@/charterafrica/components/PostCard

### ISSUE THREAD

**Issue by kilemensi** [CodeForAfrica/ui#307]
## Description

Implement a Reusable `PostCard` component that can be used to show News and Research posts/articles. The component needs:

1. title prop (limited to a 3 lines),
2. author prop (optional, single line), and
3. date (single line).

## Screenshot

![Image](https://user-images.githubusercontent.com/1779590/215458765-8ba31cfc-04bf-4692-9e81-8d2a58a92ee2.png)

**Comment by koechkevin** [comment]
@kilemensi is image prop not required here?

**Comment by kilemensi** [comment]
It is @koechkevin. I only listed those that need limitation/constraints.

**Comment by kilemensi** [comment]
@koechkevin please update PR description when fixing an issue. e.g. #318 [should have](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) closed this issue when merged.

Fixed by #318
