### ISSUE TITLE
@/charterafrica/pages/ErrorPage

### ISSUE THREAD

**Issue by kilemensi** [CodeForAfrica/ui#319]
## Description

Implement the error pages per [designs](https://www.figma.com/file/gbnaO1FYPq16V2gAFbLOkl/CfA---EPD-Charter-Africa---Sep-2022?node-id=9313%3A29587&t=gHql57tAK6HPaLGe-0). Things to keep in mind:

  1. Content of these pages should be editable in the CMS to allow localisation.
  2. 404 [needs to be static](https://nextjs.org/docs/advanced-features/custom-error-page#404-page). Current config seem to have issue with static building (could be because we run Payload and Next.js in the same server) & hence we may need a temporary solution e.g. hard-code 404 content to the page.
  3. BackgrondBox component can be reused here by customising `bgcolor` and `backgroundImage`.

**Comment by koechkevin** [comment]
https://nextjs.org/docs/advanced-features/custom-error-page
