### ISSUE TITLE
@/charterafrica YouTube integration

### ISSUE THREAD

**Issue by kilemensi** [CodeForAfrica/ui#369]
## Description

In order to build the consultation tool, we need ability to pull videos/audios from YouTube **_with_** their comments.

The task is to do a quick investigation to figure out what is the best way to go about this:

1. Does video embed include comments?
2. If not, how can you pull comments given a video id or url?
3. What is the best way of pulling multiple videos/audios? Example could be pulling from a playlist, or a channel, etc.

At the end of the day, we'd need to build #335. (Please see Figma for any design updates).

**Comment by kilemensi** [comment]
cc @kelvinkipruto , @koechkevin

**Comment by koechkevin** [comment]
here is a [document link](https://docs.google.com/document/d/1DMM9x-SRgwD9yEMPMkD0dK7awS69cnsgdNs48kc3J8A/edit?usp=sharing) to implementation plan.

We may need to make use of Google API to achieve desired goal.

cc @kilemensi @kelvinkipruto
