### ISSUE TITLE
@/charterafrica sourceAFRICA Integration

### ISSUE THREAD

**Issue by kilemensi** [CodeForAfrica/ui#370]
## Description

In order to build the consultation tool, we need ability to pull documents from [sourceAFRICA](https://sourceafrica.net) **_with_** their comments (`notes` in sourceAFRICA speak).

The task is to do a quick investigation to figure out what is the best way to go about this:

1. sourceAFRICA offers ability to embed a full document. Does the embedded document include comments?
2. If not, does sourceAFRICA offers API to pull comments for a given document?
3. What is the best way of pulling multiple documents? Pulling everything in project, group, etc.

At the end of the day, we'd need to build [this](https://www.figma.com/file/gbnaO1FYPq16V2gAFbLOkl/CfA---EPD-Charter-Africa---Sep-2022?node-id=9849-61203&t=LEJtqtuWqunnSk2v-0) page.

Some helpful links

- API documentation: https://dc.sourceafrica.net/help/api
- outbreak.AFRICA [repo](https://github.com/CodeForAfrica/outbreak.AFRICA): outbreak.AFRICA contains sourceAFRICA integration we developed back in 2020. It could serve as a starting point.

**Comment by kilemensi** [comment]
cc @koechkevin , @kelvinkipruto

**Comment by kelvinkipruto** [comment]
The implementation details doc is [here](https://docs.google.com/document/d/1Y590vWupZCNhidTa83ds_Nsz8ND2r0O54SEzKqFSCyQ/edit?usp=sharing)
