### ISSUE TITLE
@/charterafrica Github Integration

### ISSUE THREAD

**Issue by koechkevin** [CodeForAfrica/ui#400]
Research on Github Integration. This issue seeks to answer the following questions

1. What is the rate limit for github integration
2. How can we best implement Github API consuption.

## List of tasks to be completed
- [ ] Create a function that takes in google sheet `URL`, `Sheet Title` uses google API to get contents and returns JSON formated response of data in the sheet.
- [ ] Create a utility function to query github API. Usage `Import { getRepoDetails } from "./github"`.
- [ ] Create payload Collections as per 
![final](https://user-images.githubusercontent.com/39160236/230071572-14a6ea57-d0b2-4c6d-ad7a-7f130d968f49.png)
and their respective update/create functions
- [ ] Create an API endpoint that will be executed as a cron. Hitting this API endpoint with no parameters will read payload globals gsheet ID and sheet to read data from and perform data processing.

**Comment by koechkevin** [comment]
@kilemensi @kelvinkipruto please have a look at this brief document on Github API implementation https://docs.google.com/document/d/1HWTZnT8k4I1amePonIdXuUrOvj-oOG9yPAJXaSNJkJo/edit?usp=sharing

**Comment by koechkevin** [comment]
@kilemensi The above document has been updated.

**Comment by kilemensi** [comment]
Is this different from https://github.com/CodeForAfrica/ui/issues/438 @koechkevin ?

**Comment by kilemensi** [comment]
This is now done @koechkevin
