### ISSUE TITLE
@/charterafrica | Github Integration | Components |Tools, Organisation and Contributors

### ISSUE THREAD

**Issue by koechkevin** [CodeForAfrica/ui#413]
- [x] [Add tools list item components](https://www.figma.com/file/gbnaO1FYPq16V2gAFbLOkl/CfA---EPD-Charter-Africa---Sep-2022?node-id=11922-106258&t=C0e9SrM6I5rxQEoE-4)
- [x] [Add organisation list item coponents](https://www.figma.com/file/gbnaO1FYPq16V2gAFbLOkl/CfA---EPD-Charter-Africa---Sep-2022?node-id=11922-109434&t=C0e9SrM6I5rxQEoE-4)
- [x] [Add contributor list item components](https://www.figma.com/file/gbnaO1FYPq16V2gAFbLOkl/CfA---EPD-Charter-Africa---Sep-2022?node-id=11922-109450&t=C0e9SrM6I5rxQEoE-4)
- [x] Integrate with data fetched from PR #404 
- [x] [Organsation view page](https://www.figma.com/file/gbnaO1FYPq16V2gAFbLOkl/CfA---EPD-Charter-Africa---Sep-2022?node-id=11922-106366&t=C0e9SrM6I5rxQEoE-4)
- [x] [Tool view page](https://www.figma.com/file/gbnaO1FYPq16V2gAFbLOkl/CfA---EPD-Charter-Africa---Sep-2022?node-id=11922-106366&t=C0e9SrM6I5rxQEoE-4)

**Comment by koechkevin** [comment]
@kilemensi This is the breakdown for Github integration components.

**Comment by kilemensi** [comment]
This is now done @koechkevin
