### ISSUE TITLE
Allow Multiple Groups for sourceAfrica documents

### ISSUE THREAD

**Issue by kelvinkipruto** [CodeForAfrica/ui#431]
Allow creation of multiple sourceAfrica groups for use in different sections of the CMS

**Comment by kilemensi** [comment]
#342 doesn't fix this @kelvinkipruto .

To clarify, multiple sourceAFRICA integration requires 2 type of integrations:
1. Just sourceAFRICA integration i.e. current `EmbeddedDocuments` implementation
2. Combined sourceAFRICA + openAFRICA integration. What we need to implement i.e. allow users to switch between Documents and Datasets views.

**Comment by kilemensi** [comment]
@kelvinkipruto

**Comment by kilemensi** [comment]
Is this different from https://github.com/CodeForAfrica/ui/issues/441 @kelvinkipruto ?

**Comment by kelvinkipruto** [comment]
@kilemensi Yes. This should have been closed with #432
