### ISSUE TITLE
Github

### ISSUE THREAD

**Issue by koechkevin** [CodeForAfrica/ui#438]
Adds a file github.js .

- Export functions that fetches repository, organisation and user data respectively.
- Handle Errors with fetching and post to Sentry
- Make use of [Conditional Requests](https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#conditional-requests).
- Expose functionality to update ecosystem list (Pull content from github and update the collection list locally)

**Comment by kilemensi** [comment]
This is now done @koechkevin
