### ISSUE TITLE
Pining documents

### ISSUE THREAD

**Issue by kelvinkipruto** [CodeForAfrica/ui#462]
We should introduce a new feature that allows pinning specific documents at the top of the document list when rendered. This feature will provide editors with the ability to designate certain documents as pinned in the CMS, ensuring they are displayed at the top of the document list always.

**Proposed Solution**
To implement this feature, the following steps can be taken:

1. CMS Enhancement:
Introduce a new field in the document block in the CMS that allows editors to enter the titles of the documents they wish to pin.
2. Fetching Documents:
When fetching documents from the API, we use the search endpoint with a query parameter that searches for the specified titles. For example:
`search.json?q=title:"Kenya Country Brochure Agoa Final"`
3. Rendering the Document List:
Sort the fetched documents in a way that places the pinned documents at the top of the list.
Display the pinned documents first, followed by the remaining documents in their default order.

**Comment by kilemensi** [comment]
@kelvinkipruto 

1. Are we pinning a single document or multiple documents? How are they supposed to look on the front-end?
2. Why accept titles? Isn't this feature very similar to how one sets a featured video on consultation page? i.e. We pull list of videos from the entered playlist and show them as options in a select field. I'm assuming here we'll pull list of documents from the entered groupId.

**Comment by kelvinkipruto** [comment]
@kilemensi I think we should allow the pinning of multiple documents. They will appear no different on the front-end, just at the top of the list.
I think being able to select from the available list of documents.

**Comment by kelvinkipruto** [comment]
@kilemensi Sarah has confirmed that they should just appear at the top of the document list

**Comment by kilemensi** [comment]
> @kilemensi Sarah has confirmed that they should just appear at the top of the document list

Can you ping me in that convo @kelvinkipruto? This is not how pinning works.
