### ISSUE TITLE
BUG: Can't create multiple pages on a new database

### ISSUE THREAD

**Issue by kelvinkipruto** [CodeForAfrica/ui#473]
**Describe the bug**
When running a clean installation of `charterafrica`, you can only create one page. Trying to create a second page fails with error:
```
{
    "errors": [
        {
            "name": "ValidationError",
            "message": "The following field is invalid: blocks.filterBar.sort.options.value",
            "data": [
                {
                    "message": "Value must be unique",
                    "field": "blocks.filterBar.sort.options.value"
                }
            ]
        }
    ]
}
```

**To Reproduce**
Steps to reproduce the behaviour:

1. Switch to the main branch
2. Update the `MONGO_URL` environment variable to point to a clean database
3. Run `charterafrica` and log in to the admin
4. Try creating more than 1 page

**Expected behaviour**
You should be able to create more than 1 page.

**Comment by kilemensi** [comment]
You're an SWE @kelvinkipruto, "fails with some errors" is not good enough. You can check logs/console and include exact error message with the issue.
