### ISSUE TITLE
@/codeforafrica global Footer

### ISSUE THREAD

**Issue by kilemensi** [CodeForAfrica/ui#508]
### Description

Implement `Footer` global in the Payload an use it to power the existing front-end. Use @/charterafrica global `Footer` as starting point but do improve it if situation necessitates.

Implementation should also keep in mind https://github.com/CodeForAfrica/ui/pull/443 since this approach promises to minimise changes should content editors choose to move blocks around.

Current content: https://github.com/CodeForAfrica/ui/blob/main/apps/codeforafrica/content/settings/footer.md

**Comment by damolaoladipo** [comment]
**User Stories:**

1.  As a visitor, I want to access important links and information conveniently in the global footer, so I can quickly navigate to key sections like About Us, Contact, and Privacy Policy from any page.
2. As a user, I want the global footer to be visually consistent with the overall website design, so I can easily identify and use it on any page.
3. As a content manager, I want the ability to easily update the content in the global footer, so I can keep it relevant and up-to-date without technical assistance.
4. As a mobile user, I want the global footer to be responsive and mobile-friendly, so I can access its contents on various devices without horizontal scrolling.
5. As a marketing team member, I want to have the option to include important call-to-action links in the global footer, so I can drive users to specific conversion points.
6. As a user, I want the global footer to load quickly, so it doesn't negatively impact the overall page load time and user experience.


**Acceptance Criteria:**

1. The global footer should be consistently placed at the bottom of every page on the website.
2. The global footer should contain links to essential pages such as About Us, Contact, Privacy Policy, and Terms of Service.
3. The content in the global footer should be editable through a content management system (CMS) or other easy-to-use tools, without requiring direct code changes.
4. The global footer should be fully responsive and adapt to different screen sizes and orientations on various devices, including mobile phones and tablets.
5. The design of the global footer should align with the overall website theme, including fonts, colors, and spacing.
6. The global footer should load independently and not delay the loading of the main content on the page.
7.  Links in the global footer should be clickable and direct users to the specified pages without any broken links.
8. The global footer should not interfere with any website functionality or obstruct important content on smaller screens.
