### ISSUE TITLE
@/codeforafrica global Navigation

### ISSUE THREAD

**Issue by kilemensi** [CodeForAfrica/ui#509]
### Description

Implement `Navigation` global in the Payload an use it to power the existing front-end. Use @/charterafrica global `Navigation` as starting point but do improve it if situation necessitates.

Implementation should also keep in mind https://github.com/CodeForAfrica/ui/pull/443 since this approach promises to minimise changes should content editors choose to move blocks around.

Current content: https://github.com/CodeForAfrica/ui/blob/main/apps/codeforafrica/content/settings/header.md

**Comment by damolaoladipo** [comment]
**User Stories:**
1. As a website visitor, I want a clear and intuitive global navigation menu, so I can easily access different sections of the website.
2. As a user, I want the global navigation to be consistent across all pages, so I can quickly find what I need, regardless of where I am on the website.
3. As a mobile user, I want the global navigation to be responsive and accessible from my mobile device, so I can navigate the website on the go.
4. As a new user, I want the global navigation labels to be clear and descriptive, so I can understand the content and purpose of each section.
5. As a returning user, I want the global navigation to be prominently placed, so I can easily locate it and avoid unnecessary scrolling or searching.
6. As a customer, I want the global navigation to include a link to the "Contact Us" page, so I can easily reach out for support or inquiries.

**Acceptance Criteria:**
1. The global navigation menu should be visible and accessible on all pages of the website.
2. The global navigation menu should have a consistent layout and design throughout the website.
3. The global navigation menu should collapse and transform into a mobile-friendly menu for smaller screen sizes.
4.  The global navigation menu should be tested on different devices and browsers to ensure responsiveness and compatibility.
5. The global navigation should be thoroughly tested during and after the website migration to ensure all links and functionalities are working as expected.
6. The global navigation should be visually appealing and consistent with the overall website design and branding.
