### ISSUE TITLE
@hurumap/core/LineChart

### ISSUE THREAD

**Issue by m453h** [CodeForAfrica/ui#808]
Move LineChart to Hurumap-Core

**Comment by kilemensi** [comment]
There is also this comment left by @Arame93:

>Issue while attempting to produce a line chart for the HURUmap using the Django admin. Despite following the standard procedures, we are unable to generate the desired chart. When trying to create a line chart, the graph fails to render as shown on the screenshot. I have done some researches to try to fix it but it seems to be a site configuration problem.

Whoever is working on this issue, please reach out to her (here or in Slack) to figure out what is/was the issue.

**Comment by m453h** [comment]
@kilemensi I'm working on this... @Arame93 I would like to know more about the chart you were attempting to generate
