### ISSUE TITLE
@vpnmanager Data transfer statistics

### ISSUE THREAD

**Issue by koechkevin** [CodeForAfrica/ui#875]
Currently, Outline vpn manager statistics are generated monthly by running [this script](https://github.com/CodeForAfrica/api/blob/011d319a9d6153943889108233993bbf7bc5e452/cfa_vpn/py/vpn.py#L87).
```sh
dist/cfa_vpn.py/outline_manager.pex -e
```
Propose a solution that allows a user get these stats easily without always having the intervention of tech team devs.

**Comment by kilemensi** [comment]
I think this should be marked as done @koechkevin
