### ISSUE TITLE
Fix CivicSignal preview issues on ResearchBlog

### ISSUE THREAD

**Issue by m453h** [CodeForAfrica/ui#907]

**Comment by kilemensi** [comment]
Wasn't this done @m453h ?

**Comment by m453h** [comment]
This is partially done, we have fixed the preview issue but the sub-issue  #998 for Live Preview hasn't been done

**Comment by kilemensi** [comment]
Cool, then lets covert #998 into a standalone issue and close this one @m453h rather than keeping both open.
