### ISSUE TITLE
ClimateMapped Footer

### ISSUE THREAD

**Issue by kelvinkipruto** [CodeForAfrica/ui#923]
Create a footer for ClimateMapped.

Request Link: [Feature 3](https://docs.google.com/document/d/1TUrdCRnbj6TSqiuwITKUpnDUEi_ktm_3PmgsaD0y2bw/edit#heading=h.ben2wg1oiafi)

> Preview
![Image](https://github.com/user-attachments/assets/f3b05344-6a57-44b6-b468-0897ad52a3af)

**Comment by RalphOwah** [comment]
Standard CfA footer [CfA text, Social Media buttons, Links to some key pages]
