### ISSUE TITLE
ClimateMapped Data Navigation Panel

### ISSUE THREAD

**Issue by kelvinkipruto** [CodeForAfrica/ui#925]
Create a navigation panel on Climatemapped Africa Similar to PesaYetu

Request Link: [Feature 5](https://docs.google.com/document/d/1TUrdCRnbj6TSqiuwITKUpnDUEi_ktm_3PmgsaD0y2bw/edit#heading=h.hbi7d1sv7wym)

> Preview
![Image](https://github.com/user-attachments/assets/1c060119-3597-4f91-83b2-59fc2772855d)

**Comment by RalphOwah** [comment]
Standard HURUmap Visualisation Navigation Panel
