### ISSUE TITLE
ClimateMapped: Improve data page navigation labels

### ISSUE THREAD

**Issue by kelvinkipruto** [CodeForAfrica/ui#926]
Improve the labelling on Navigations in the explore page in ClimateMapped

Request Link: [Feature 6](https://docs.google.com/document/d/1TUrdCRnbj6TSqiuwITKUpnDUEi_ktm_3PmgsaD0y2bw/edit#heading=h.9ih8c5e33n7n)

**Comment by kilemensi** [comment]
Implemented this as tooltip when hovering over the buttons (similar to how it's done in original Wazimap).
