### ISSUE TITLE
About and Methodology Page

### ISSUE THREAD

**Issue by kilemensi** [CodeForAfrica/ui#965]
Description:
Briefly describe the feature request:  A page that will have long text
What problem does this feature solve for the users? It will have the metadata and host the data methodology.
How the Feature Works: Page

Click link for details
https://docs.google.com/document/d/1TUrdCRnbj6TSqiuwITKUpnDUEi_ktm_3PmgsaD0y2bw/edit?usp=sharing

**Comment by kilemensi** [comment]
If we're using a single page (/about?) for both about and methodology, the [methodology](https://pesayetu.pesacheck.org/how-it-works) block/ui is the same as [history](https://pesayetu.pesacheck.org/about) block in the about (which has already been implemented in [921](https://github.com/CodeForAfrica/ui/issues/921)).

Is there anything else we need to do for this story @RalphOwah ?

**Comment by RalphOwah** [comment]
You are correct @kilemensi , #921 ticket should suffix, although I am not sure why it's being called a history block by @koechkevin 

But we need for this story in consideration is a single page with 2 block sections for long text 

1. About section
2. Methodology section

**Comment by kilemensi** [comment]
Cool, @RalphOwah, what I wanted to confirm is: should those block look like history block or not? If yes, we can add as many blocks as we need already in any page without any extra code.

Please see <https://climatemapped-africa.dev.codeforafrica.org/about>

**Comment by RalphOwah** [comment]
Yes @kilemensi the history block format works perfectly, it will also help if it allows for multimedia (images) and tables within the block considering the series of copy/content the ClimateMap team envisages for this page.

**Comment by kilemensi** [comment]
With the updated [`RichText`](https://github.com/CodeForAfrica/ui/pull/969) component, this should be done
