### ISSUE TITLE
From Country to regional navigation

### ISSUE THREAD

**Issue by koechkevin** [CodeForAfrica/ui#966]
https://docs.google.com/document/d/1TUrdCRnbj6TSqiuwITKUpnDUEi_ktm_3PmgsaD0y2bw/edit?usp=sharing

**Comment by kelvinkipruto** [comment]
@koechkevin, I believe this is already fixed with #963. We can discuss it with @RalphOwah to confirm.

**Comment by RalphOwah** [comment]
Hi @kelvinkipruto has #963 been deployed?
[](https://github.com/CodeForAfrica/ui/pull/963 )

**Comment by RalphOwah** [comment]
Hi @koechkevin this still does not work
