### ISSUE TITLE
Hero Mobile View

### ISSUE THREAD

**Issue by kilemensi** [CodeForAfrica/ui#975]
Hero doesn't match PesaYetu look in mobile

### PesaYetu
![Image](https://github.com/user-attachments/assets/cc627826-4461-4a3d-b812-27ff27d59e8d)

**Comment by koechkevin** [comment]
Styles are similar but how data was saved in pesayetu CMS as paragraphs for title I think.

**Comment by kilemensi** [comment]
Partly yes but here is also:

1. search label not appearing in mobile (it appears in desktop)
2. Issue of spacing at the bottom of after the location search component
